const IMAGES = {
    LOAD: 'IMAGE_LOAD',
    LOAD_SUCCESS: 'IMAGE_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGE_LOAD_FAILS',
};

const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'STATS_LOAD_FAILS',
};

export { IMAGES, STATS };
